---
- name: Deploy DevOps Task Manager
  hosts: local
  connection: local

  tasks:
    - name: Create deployment directory
      file:
        path: /var/lib/jenkins/deployed-app
        state: directory
        mode: '0755'

    - name: Copy application JAR
      copy:
        src: /var/lib/jenkins/workspace/devops-task-manager/target/devops-task-manager-1.0-SNAPSHOT.jar
        dest: /var/lib/jenkins/deployed-app/devops-task-manager.jar
